graph TD;
    Iter4["Iteration 4: n = 3<br>Start: 1 -> End: 3"] --> Iter2["Iteration 2: n = 2<br>Start: 1 -> End: 2"]
    Iter2 --> Iter1["Iteration 1: n = 1<br>Start: 1 -> End: 3"]
    Iter2 --> Iter3["Iteration 3: n = 1<br>Start: 3 -> End: 2"]

    Iter4 --> Iter6["Iteration 6: n = 2<br>Start: 2 -> End: 3"]
    Iter6 --> Iter5["Iteration 5: n = 1<br>Start: 2 -> End: 1"]
    Iter6 --> Iter7["Iteration 7: n = 1<br>Start: 1 -> End: 3"]
